import cart from "./modules/cart";
import load from "./modules/load";
import search from "./modules/search";
import catalog from "./modules/catalog";
//import priceFilter from "./modules/priceFilter";
//import getData from "./modules/second";
cart();
load();
search();
catalog();
//priceFilter();
